<?php

/*
 * Table Definition for marca - formulario
 */

class DataObjects_Marca 
 {

    // you can define these yourself

    var $__table = 'marca';                       // table name
    var $id_marca;                                 // int primary_key
    var $nom_marca;
    var $referencia_marca;                              // string
    var $fecha_marca;

    // these are usefull to be consistant with a autogenerated file.

    /* Static get */

    function staticGet($k, $v = NULL) {
        return DB_DataObject::staticGet('DataObject_Marca', $k, $v);
    }

 
    function table() {
        return array(
            'id_marca' => DB_DATAOBJECT_INT,
            'nom_marca' => DB_DATAOBJECT_STR,
            'referencia_marca' => DB_DATAOBJECT_STR,
            'fecha_marca' => DB_DATAOBJECT_STR + DB_DATAOBJECT_DATE + DB_DATAOBJECT_TIME + DB_DATAOBJECT_NOTNULL,
        );
    }
  
    function keys() {
        return array('id');
    }

    function sequenceKey() { // keyname, use native, native name
        return array(false, false, false);
    }
    //define llaves foraneas
    function links() {
        $links = array();
        $links["id"] = "";
        return $links;
    }
}
?>